# Generated by Django 3.0 on 2019-12-18 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sggucdnm', models.CharField(max_length=8)),
                ('yadmnm', models.CharField(max_length=15)),
                ('clcdnm', models.CharField(max_length=6)),
                ('npaykornm', models.CharField(max_length=25)),
                ('maxprc', models.IntegerField(max_length=8)),
                ('minprc', models.IntegerField(max_length=8)),
                ('url', models.URLField()),
                ('sidocdnm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.City')),
            ],
        ),
    ]
