# Generated by Django 3.0 on 2019-12-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='maxprc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='minprc',
            field=models.IntegerField(),
        ),
    ]
