# Generated by Django 3.0 on 2019-12-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20191218_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='hospital강원',
            options={'verbose_name_plural': 'Hospital강원'},
        ),
        migrations.AlterModelOptions(
            name='hospital경기',
            options={'verbose_name_plural': 'Hospital경기'},
        ),
        migrations.AlterModelOptions(
            name='hospital경남',
            options={'verbose_name_plural': 'Hospital경남'},
        ),
        migrations.AlterModelOptions(
            name='hospital경북',
            options={'verbose_name_plural': 'Hospital경북'},
        ),
        migrations.AlterModelOptions(
            name='hospital광주',
            options={'verbose_name_plural': 'Hospital광주'},
        ),
        migrations.AlterModelOptions(
            name='hospital대구',
            options={'verbose_name_plural': 'Hospital대구'},
        ),
        migrations.AlterModelOptions(
            name='hospital대전',
            options={'verbose_name_plural': 'Hospital대전'},
        ),
        migrations.AlterModelOptions(
            name='hospital부산',
            options={'verbose_name_plural': 'Hospital부산'},
        ),
        migrations.AlterModelOptions(
            name='hospital서울',
            options={'verbose_name_plural': 'Hospital서울'},
        ),
        migrations.AlterModelOptions(
            name='hospital세종시',
            options={'verbose_name_plural': 'Hospital세종시'},
        ),
        migrations.AlterModelOptions(
            name='hospital울산',
            options={'verbose_name_plural': 'Hospital울산'},
        ),
        migrations.AlterModelOptions(
            name='hospital인천',
            options={'verbose_name_plural': 'Hospital인천'},
        ),
        migrations.AlterModelOptions(
            name='hospital전남',
            options={'verbose_name_plural': 'Hospital전남'},
        ),
        migrations.AlterModelOptions(
            name='hospital전북',
            options={'verbose_name_plural': 'Hospital전북'},
        ),
        migrations.AlterModelOptions(
            name='hospital충남',
            options={'verbose_name_plural': 'Hospital충남'},
        ),
        migrations.AlterModelOptions(
            name='hospital충북',
            options={'verbose_name_plural': 'Hospital충북'},
        ),
        migrations.AddField(
            model_name='hospital강원',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital경기',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital경남',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital경북',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital광주',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital대구',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital대전',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital부산',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital서울',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital세종시',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital울산',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital인천',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital전남',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital전북',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital충남',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital충북',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hospital강원',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital경기',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital경남',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital경북',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital광주',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital대구',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital대전',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital부산',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital서울',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital세종시',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital울산',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital인천',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital전남',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital전북',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital충남',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='hospital충북',
            name='sidocdnm',
            field=models.CharField(max_length=8),
        ),
    ]
